### ISSUE TITLE
Problem downloading files

### ISSUE THREAD

**Issue by saberraz** [Gugym/qgis-plugin-edr#50]
![image](https://github.com/Gugym/qgis-plugin-edr/assets/2649047/fdbc4ca9-9b34-441d-bcf8-edfab7314a5f)

Plugin version: 0.12.0

- Download folder is writable
- There is enough storage

**Comment by MattWardle** [comment]
Should I try removing the saved servers and adding again?

**Comment by saberraz** [comment]
Could you please test the followings:
- Does this happen with the previous version of the plugin (you can downgrade your plugin from the Plugin Manager to test it)?
- Does it happen with all servers?

**Comment by MattWardle** [comment]
Hmm. Something weird going on. Is my QGIS version now too old for the official plugin repo?
![image](https://github.com/Gugym/qgis-plugin-edr/assets/17428149/2fc8a388-a9ac-4e98-88f6-8d23c77e4b98)

**Comment by saberraz** [comment]
From the screenshot, it seems your internet settings have changed (maybe updated proxy) and you do not have access to the internet from within QGIS.

Could you go to Settings > Options > Network and enable proxy, then select DefaultProxy:
![image](https://github.com/Gugym/qgis-plugin-edr/assets/2649047/9198b2fd-e3aa-43a3-9d6d-3dcbc4903c58)

**Comment by MattWardle** [comment]
Not a problem after all! normal internet = everything works.
